export const COLORS = {
  primary: '#22C55E',
  primaryLight: '#4ADE80',
  primaryDark: '#16A34A',
  secondary: '#FBBF24',
  secondaryLight: '#FEF3C7',
  background: '#F7FAF8',
  surface: '#FFFFFF',
  surfaceAlt: '#F1F5F3',
  text: '#0F172A',
  textSecondary: '#475569',
  textLight: '#94A3B8',
  border: 'rgba(15, 23, 42, 0.08)',
  borderLight: '#EDF2F0',
  success: '#22C55E',
  warning: '#F59E0B',
  error: '#EF4444',
  info: '#60A5FA',
  white: '#FFFFFF',
  black: '#000000',
  attendance: '#60A5FA',
  laboratory: '#A78BFA',
  quiz: '#FBBF24',
  exam: '#F87171',
  assignment: '#FB923C',
  draft: '#94A3B8',
  readyToSign: '#F59E0B',
  signed: '#22C55E',
  locked: '#334155',
  corrected: '#EF4444',
  archived: '#CBD5E1',
};

export const CATEGORY_COLORS: Record<string, string> = {
  ATTENDANCE: COLORS.attendance,
  LABORATORY: COLORS.laboratory,
  QUIZ: COLORS.quiz,
  EXAM: COLORS.exam,
  ASSIGNMENT: COLORS.assignment,
};

export const STATUS_COLORS: Record<string, string> = {
  draft: COLORS.draft,
  ready_to_sign: COLORS.readyToSign,
  signed: COLORS.signed,
  locked: COLORS.locked,
  corrected: COLORS.corrected,
  archived: COLORS.archived,
};