-- ClassKard cloud schema (Postgres / Supabase)

-- ============================================================
-- users (profiles table, linked 1:1 to auth.users)
-- ============================================================
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_id uuid unique references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  role text not null check (role in ('teacher','student','admin')),
  signature_data text,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

create policy "users can read own profile"
on public.users for select
using (auth_id = auth.uid());

create policy "users can update own profile"
on public.users for update
using (auth_id = auth.uid())
with check (auth_id = auth.uid());

-- ============================================================
-- academic_years
-- ============================================================
create table if not exists public.academic_years (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  end_date date not null,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);

alter table public.academic_years enable row level security;

create policy "years readable by all users"
on public.academic_years for select
using (auth.uid() is not null);

create policy "years writable by teachers"
on public.academic_years for all
using (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'teacher'))
with check (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'teacher'));

-- ============================================================
-- subjects
-- ============================================================
create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  description text not null default '',
  created_at timestamptz not null default now()
);

alter table public.subjects enable row level security;

create policy "subjects readable by all users"
on public.subjects for select
using (auth.uid() is not null);

create policy "subjects writable by teachers"
on public.subjects for all
using (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'teacher'))
with check (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'teacher'));

-- ============================================================
-- students
-- ============================================================
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id),
  student_number text not null unique,
  first_name text not null,
  middle_name text not null default '',
  last_name text not null,
  status text not null default 'active' check (status in ('active','archived')),
  created_at timestamptz not null default now()
);

alter table public.students enable row level security;

create policy "students readable by teachers"
on public.students for select
using (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'teacher'));

create policy "student reads own profile"
on public.students for select
using (user_id = (select u.id from public.users u where u.auth_id = auth.uid()));

create policy "students writable by teachers"
on public.students for all
using (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'teacher'))
with check (exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'teacher'));

-- ============================================================
-- sections
-- ============================================================
create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  academic_year_id bigint not null references public.academic_years(id),
  subject_id bigint not null references public.subjects(id),
  teacher_id bigint not null references public.users(id),
  name text not null,
  class_code text not null unique,
  enrollment_mode text not null default 'approval' check (enrollment_mode in ('approval','auto')),
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);

alter table public.sections enable row level security;

-- anyone (loggen-in) can look up a section by class code / name
create policy "sections readable by all users"
on public.sections for select
using (auth.uid() is not null);

-- enrollment is handled through the enrollments table below, so only teachers
-- may insert/update/delete section rows.
create policy "sections writable by owner teacher"
on public.sections for all
using (
  exists (
    select 1 from public.users u
    where u.auth_id = auth.uid() and u.role = 'teacher' and u.id = teacher_id
  )
)
with check (
  exists (
    select 1 from public.users u
    where u.auth_id = auth.uid() and u.role = 'teacher' and u.id = teacher_id
  )
);

-- ============================================================
-- enrollments
-- ============================================================
create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id),
  section_id bigint not null references public.sections(id),
  effective_from date not null default current_date,
  effective_to date,
  status text not null default 'pending' check (status in ('pending','approved','active','completed','dropped','revoked')),
  created_at timestamptz not null default now(),
  unique (student_id, section_id)
);

alter table public.enrollments enable row level security;

-- a student may create an enrollment for themselves (join a class)
create policy "student may enroll self"
on public.enrollments for insert
with check (
  exists (
    select 1 from public.students st
    join public.users u on u.id = st.user_id
    where u.auth_id = auth.uid() and st.id = student_id
  )
  or exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'teacher')
);

-- student can read their own enrollments
create policy "students read own enrollments"
on public.enrollments for select
using (
  exists (
    select 1 from public.students st
    join public.users u on u.id = st.user_id
    where u.auth_id = auth.uid() and st.id = student_id
  )
);

-- teacher can read enrollments for sections they own
create policy "teacher reads own section enrollments"
on public.enrollments for select
using (
  exists (
    select 1 from public.sections s
    join public.users u on u.id = s.teacher_id
    where u.auth_id = auth.uid() and s.id = section_id
  )
);

-- teacher can update/delete enrollments for sections they own
create policy "teacher manages own section enrollments"
on public.enrollments for update
using (
  exists (
    select 1 from public.sections s
    join public.users u on u.id = s.teacher_id
    where u.auth_id = auth.uid() and s.id = section_id
  )
)
with check (
  exists (
    select 1 from public.sections s
    join public.users u on u.id = s.teacher_id
    where u.auth_id = auth.uid() and s.id = section_id
  )
);

create policy "teacher deletes own section enrollments"
on public.enrollments for delete
using (
  exists (
    select 1 from public.sections s
    join public.users u on u.id = s.teacher_id
    where u.auth_id = auth.uid() and s.id = section_id
  )
);

-- ============================================================
-- records
-- ============================================================
create table if not exists public.records (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id),
  section_id bigint not null references public.sections(id),
  category text not null check (category in ('ATTENDANCE','LABORATORY','QUIZ','EXAM','ASSIGNMENT')),
  record_type text not null default '',
  title text not null default '',
  date date not null default current_date,
  score numeric,
  total_score numeric,
  percentage numeric,
  status text not null default 'draft' check (status in ('draft','ready_to_sign','signed','locked','corrected','archived')),
  remarks text not null default '',
  attendance_status text,
  time_in text,
  time_out text,
  due_date date,
  created_by bigint not null references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  signed_by bigint references public.users(id),
  signed_at timestamptz,
  signature_data text,
  locked_at timestamptz
);

alter table public.records enable row level security;

-- teacher can read/write records for their own sections
create policy "teacher reads own records"
on public.records for select
using (
  exists (
    select 1 from public.sections s
    join public.users u on u.id = s.teacher_id
    where u.auth_id = auth.uid() and s.id = section_id
  )
);

create policy "teacher inserts own records"
on public.records for insert
with check (
  exists (
    select 1 from public.sections s
    join public.users u on u.id = s.teacher_id
    where u.auth_id = auth.uid() and s.id = section_id
  )
);

create policy "teacher updates own records"
on public.records for update
using (
  exists (
    select 1 from public.sections s
    join public.users u on u.id = s.teacher_id
    where u.auth_id = auth.uid() and s.id = section_id
  )
);

-- student can read their own records
create policy "student reads own records"
on public.records for select
using (
  exists (
    select 1 from public.students st
    join public.users u on u.id = st.user_id
    where u.auth_id = auth.uid() and st.id = student_id
  )
);

-- ============================================================
-- audit_logs
-- ============================================================
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  record_id bigint references public.records(id),
  actor_id bigint not null references public.users(id),
  action text not null,
  old_value text,
  new_value text,
  reason text not null default '',
  created_at timestamptz not null default now()
);

alter table public.audit_logs enable row level security;

-- audit logs viewable by teachers and by the actor themselves
create policy "audit logs readable"
on public.audit_logs for select
using (
  actor_id = (select u.id from public.users u where u.auth_id = auth.uid())
  or exists (select 1 from public.users u where u.auth_id = auth.uid() and u.role = 'teacher')
);

create policy "audit logs insertable by users"
on public.audit_logs for insert
with check (
  actor_id = (select u.id from public.users u where u.auth_id = auth.uid())
);

-- ============================================================
-- helpers / indexes
-- ============================================================
create index if not exists idx_students_user on public.students(user_id);
create index if not exists idx_enrollments_section on public.enrollments(section_id);
create index if not exists idx_enrollments_student on public.enrollments(student_id);
create index if not exists idx_records_student on public.records(student_id);
create index if not exists idx_records_section on public.records(section_id);